// Generated by CoffeeScript 1.6.3
exports.create = function(root, parentControl) {
  var context, notice, stack;
  context = root.context;
  stack = context.stack, notice = context.notice;
  return function(done, injectionControl) {
    var parent, startedAt;
    parent = stack[stack.length - 1];
    if (parent != null) {
      done();
      return process.nextTick(function() {
        return parent.deferral.resolve();
      });
    } else {
      startedAt = context.walking.startedAt;
      context.walking.duration = Date.now() - startedAt;
      return notice.event('phrase::recurse:end', {
        walk: context.walking
      }).then(function() {
        var firstwalk;
        if (context.walks == null) {
          context.walks = [];
          context.firstWalk = context.walking;
          firstwalk = true;
        }
        context.walks.unshift(context.walking);
        if (context.walks.length > 5) {
          context.walks.pop();
        }
        if (!firstwalk) {
          return context.tree.update().then(function() {
            delete context.walking;
            return process.nextTick(done);
          });
        }
        delete context.walking;
        return process.nextTick(done);
      });
    }
  };
};
