// Generated by CoffeeScript 1.6.3
exports.create = function(root, control) {
  var util;
  util = root.util;
  return {
    detect: function(phrase, isLeaf) {
      var arg1;
      arg1 = (function() {
        try {
          return util.argsOf(phrase.fn)[0];
        } catch (_error) {}
      })();
      if ((arg1 != null) && control.leaf.indexOf(arg1) >= 0) {
        phrase.leaf = true;
        return isLeaf(true);
      }
      phrase.leaf = false;
      return isLeaf(false);
    }
  };
};
