// Generated by CoffeeScript 1.6.3
exports.createClass = function(root) {
  var PhraseGraphChangeSet;
  return PhraseGraphChangeSet = (function() {
    function PhraseGraphChangeSet() {}

    return PhraseGraphChangeSet;

  })();
};
