// Generated by CoffeeScript 1.6.3
exports.create = function(root, parentControl) {
  var context, notice, stack;
  context = root.context;
  stack = context.stack, notice = context.notice;
  return function(done, injectionControl) {
    var parent, startedAt;
    parent = stack[stack.length - 1];
    if (parent != null) {
      done();
      return process.nextTick(function() {
        return parent.deferral.resolve();
      });
    } else {
      startedAt = context.walking.startedAt;
      context.walking.duration = Date.now() - startedAt;
      return notice.event('phrase::recurse:end', context.walking).then(function() {
        var firstwalk;
        if (context.walks == null) {
          context.walks = [];
          context.firstWalk = context.walking;
          firstwalk = true;
        }
        context.walks.unshift(context.walking);
        if (context.walks.length > 5) {
          context.walks.pop();
        }
        if (firstwalk == null) {
          console.log('\nCHANGED_GRAPH');
          console.log('ORIGINAL', JSON.stringify(context.graph.vertices, null, 2));
          console.log('NEW', JSON.stringify(context.graphs.latest.vertices, null, 2));
          delete context.walking;
          return process.nextTick(done);
        }
        delete context.walking;
        console.log({
          WALKING: context.walking
        });
        return process.nextTick(done);
      });
    }
  };
};
