// Generated by CoffeeScript 1.6.3
exports.create = function(root, parentControl) {
  var context, notice, stack;
  context = root.context;
  stack = context.stack, notice = context.notice;
  return function(done, injectionControl) {
    stack.pop();
    return done();
  };
};
