// Generated by CoffeeScript 1.6.3
exports.create = function(root) {
  var context, emitter, stack;
  context = root.context;
  stack = context.stack, emitter = context.emitter;
  return function(done) {
    stack.pop();
    return done();
  };
};
