// Generated by CoffeeScript 1.6.3
exports.create = function(root) {
  var context, emitter, hooks;
  context = root.context;
  emitter = context.emitter, hooks = context.hooks;
  return function(done, injectionControl) {
    var afterAll, afterEach, beforeAll, beforeEach;
    emitter.emit('phrase::start');
    beforeAll = hooks.beforeAll.pop();
    beforeEach = hooks.beforeEach.pop();
    afterEach = hooks.afterEach.pop();
    afterAll = hooks.afterAll.pop();
    injectionControl.beforeEach || (injectionControl.beforeEach = beforeEach);
    injectionControl.beforeAll || (injectionControl.beforeAll = beforeAll);
    injectionControl.afterEach || (injectionControl.afterEach = afterEach);
    injectionControl.afterAll || (injectionControl.afterAll = afterAll);
    if (typeof injectionControl.beforeAll !== 'function') {
      return done();
    }
    injectionControl.beforeAll();
    return done();
  };
};
