// Generated by CoffeeScript 1.6.3
exports.create = function(root) {
  var context, hooks, notice;
  context = root.context;
  notice = context.notice, hooks = context.hooks;
  return function(done, injectionControl) {
    var afterAll, afterEach, beforeAll, beforeEach;
    beforeAll = hooks.beforeAll.pop();
    beforeEach = hooks.beforeEach.pop();
    afterEach = hooks.afterEach.pop();
    afterAll = hooks.afterAll.pop();
    injectionControl.beforeEach = beforeEach;
    injectionControl.beforeAll = beforeAll;
    injectionControl.afterEach = afterEach;
    injectionControl.afterAll = afterAll;
    return done();
  };
};
