// Generated by CoffeeScript 1.6.3
var Phrase;

Phrase = require('../../phrase');

exports.create = function(root) {
  var context, emitter, stack;
  context = root.context;
  stack = context.stack, emitter = context.emitter;
  return function(done, injectionControl) {
    var defer, phrase, phraseControl, phraseFn, phraseText;
    defer = injectionControl.defer;
    defer.resolve();
    phraseText = typeof injectionControl.args[0] === 'function' ? {} : injectionControl.args[0];
    phraseControl = typeof injectionControl.args[1] === 'function' ? {} : injectionControl.args[1];
    phraseFn = injectionControl.args[2] || injectionControl.args[1] || injectionControl.args[0] || function() {
      return console.log('NO ARGS');
    };
    phrase = new Phrase({
      text: phraseText,
      control: phraseControl,
      fn: phraseFn
    });
    stack.push(phrase);
    injectionControl.args[0] = phraseText;
    injectionControl.args[1] = phraseControl;
    injectionControl.args[2] = phraseFn;
    return done();
  };
};
