// Generated by CoffeeScript 1.6.3
exports.create = function(root) {
  var context, emitter;
  context = root.context;
  emitter = context.emitter;
  return function(done) {
    return done();
  };
};
