// Generated by CoffeeScript 1.6.3
var AfterAll, AfterEach, BeforeAll, BeforeEach;

BeforeAll = require('./before_all');

BeforeEach = require('./before_each');

AfterEach = require('./after_each');

AfterAll = require('./after_all');

exports.bind = function(root) {
  return {
    beforeAll: BeforeAll.create(root),
    beforeEach: BeforeEach.create(root),
    afterEach: AfterEach.create(root),
    afterAll: AfterAll.create(root)
  };
};
