// Generated by CoffeeScript 1.6.3
var AfterAll, AfterEach, BeforeAll, BeforeEach;

BeforeAll = require('./before_all');

BeforeEach = require('./before_each');

AfterEach = require('./after_each');

AfterAll = require('./after_all');

exports.bind = function(root, parent) {
  return {
    beforeAll: BeforeAll.create(root, parent),
    beforeEach: BeforeEach.create(root, parent),
    afterEach: AfterEach.create(root, parent),
    afterAll: AfterAll.create(root, parent)
  };
};
