// Generated by CoffeeScript 1.6.3
exports.create = function(root) {
  var context, emitter;
  context = root.context;
  emitter = context.emitter;
  return {
    beforeAll: function(done) {
      emitter.emit('phrase::start');
      return done();
    },
    beforeEach: function(done, inject) {
      var defer;
      defer = inject.defer;
      defer.resolve();
      if (inject.args[2] == null) {
        inject.args[2] = inject.args[1] || inject.args[0] || function() {
          return console.log('NO ARGS');
        };
      }
      return done();
    },
    afterEach: function(done) {
      return done();
    },
    afterAll: function(done) {
      return done();
    }
  };
};
