// Generated by CoffeeScript 1.6.3
exports.create = function(root) {
  var util;
  util = root.util;
  return {
    detect: function(phrase, isLeaf) {
      try {
        if (util.argsOf(phrase.fn)[0] === 'end') {
          return isLeaf(true);
        }
      } catch (_error) {}
      return isLeaf(false);
    }
  };
};
