// Generated by CoffeeScript 1.6.3
exports.create = function(root) {
  var util;
  util = root.util;
  return {
    detect: function(phrase, isLeaf) {
      if (util.argsOf(phrase.fn)[0] === 'end') {
        return isLeaf(true);
      }
      return isLeaf(false);
    }
  };
};
