// Generated by CoffeeScript 1.6.3
exports.createClass = function(root) {
  var BoundryToken;
  return BoundryToken = (function() {
    function BoundryToken(params) {
      var property, _i, _len, _ref;
      this.type = 'boundry';
      this.uuid = params.uuid;
      this.signature = params.signature;
      _ref = ['type', 'uuid', 'signature'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        property = _ref[_i];
        Object.defineProperty(this, property, {
          enumerable: true,
          writable: false
        });
      }
    }

    return BoundryToken;

  })();
};
