// Generated by CoffeeScript 1.6.3
exports.createClass = function(root) {
  var BoundryToken;
  return BoundryToken = (function() {
    function BoundryToken() {
      this.type = 'boundry';
      Object.defineProperty(this, 'type', {
        enumerable: true,
        writable: false
      });
    }

    return BoundryToken;

  })();
};
