// Generated by CoffeeScript 1.6.3
exports.createClass = function(root) {
  var LeafToken;
  return LeafToken = (function() {
    function LeafToken() {
      Object.defineProperty(this, 'type', {
        enumerable: true,
        get: function() {
          return 'leaf';
        }
      });
    }

    return LeafToken;

  })();
};
