// Generated by CoffeeScript 1.6.3
exports.createClass = function(root) {
  var LeafToken;
  return LeafToken = (function() {
    function LeafToken() {
      this.type = 'leaf';
      Object.defineProperty(this, 'type', {
        enumerable: true,
        writable: false
      });
    }

    return LeafToken;

  })();
};
