// Generated by CoffeeScript 1.6.3
exports.createClass = function(root) {
  var PhraseToken;
  return PhraseToken = (function() {
    function PhraseToken(params) {
      var property, _i, _len, _ref;
      this.type = params.type;
      this.uuid = params.uuid;
      this.signature = params.signature;
      if (this.type === 'tree') {
        this.source = params.source;
        this.loaded = params.loaded;
      }
      _ref = ['uuid', 'signature'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        property = _ref[_i];
        Object.defineProperty(this, property, {
          enumerable: true,
          writable: false
        });
      }
    }

    PhraseToken.prototype.serialize = function() {
      return {
        SERIALIZE_FROM_THIS: root.context.tree.vertices[this.uuid]
      };
    };

    return PhraseToken;

  })();
};
