// Generated by CoffeeScript 1.6.3
var ProcessToken, collection;

collection = {};

ProcessToken = (function() {
  function ProcessToken(core) {
    var _this = this;
    Object.defineProperty(this, 'root', {
      enumerable: true,
      get: function() {
        return function(uuid) {
          return collection[uuid] || (collection[uuid] = {
            uuid: uuid,
            root: _this.root,
            validate: core.validate,
            inject: core.inject,
            util: core.util
          });
        };
      }
    });
  }

  return ProcessToken;

})();

module.exports = ProcessToken;
