// Generated by CoffeeScript 1.6.3
var ProcessToken, collection;

collection = {};

ProcessToken = (function() {
  function ProcessToken(core) {
    Object.defineProperty(this, 'root', {
      enumerable: true,
      get: function() {
        return function(uuid) {
          return collection[uuid] || (collection[uuid] = {
            uuid: uuid
          });
        };
      }
    });
  }

  return ProcessToken;

})();

module.exports = ProcessToken;
