// Generated by CoffeeScript 1.6.3
exports.createClass = function(root) {
  var LeafToken;
  return LeafToken = (function() {
    function LeafToken(params) {
      var property, _i, _len, _ref;
      this.type = 'root';
      this.uuid = params.uuid;
      this.signature = params.signature;
      _ref = ['type', 'uuid', 'signature'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        property = _ref[_i];
        Object.defineProperty(this, property, {
          enumerable: true,
          writable: false
        });
      }
    }

    return LeafToken;

  })();
};
