// Generated by CoffeeScript 1.6.3
exports.createClass = function(root) {
  var VertexToken;
  return VertexToken = (function() {
    function VertexToken() {
      this.type = 'vertex';
      Object.defineProperty(this, 'type', {
        enumerable: true,
        writable: false
      });
    }

    return VertexToken;

  })();
};
