// Generated by CoffeeScript 1.6.3
var Phrase;

module.exports = Phrase = (function() {
  function Phrase(properties) {
    var property;
    for (property in properties) {
      this[property] = properties[property];
    }
  }

  return Phrase;

})();
