// Generated by CoffeeScript 1.6.3
var PhraseRoot, Process;

Process = require('./core/process');

PhraseRoot = require('./phrase/root');

require('also')(exports, {}, function(core) {
  var process;
  process = new Process(core);
  return {
    createRoot: function(opts, linkFn) {
      var root;
      root = process.root(opts.uuid);
      return PhraseRoot.createClass(root).createRoot(opts, linkFn);
    }
  };
});
