// Generated by CoffeeScript 1.6.3
var defer;

defer = require('when').defer;

exports.create = function(root) {
  var context, graph, inject;
  context = root.context, inject = root.inject;
  graph = context.graph;
  return {
    graph: graph,
    run: function(opts) {
      var running;
      running = defer();
      process.nextTick(function() {
        return running.resolve([]);
      });
      return running.promise;
    }
  };
};
