// Generated by CoffeeScript 1.6.3
var PhraseRoot;

PhraseRoot = require('./phrase/root');

require('also')(exports, {}, function(core) {
  return {
    createRoot: function(opts, linkFn) {
      var phraseRoot;
      phraseRoot = PhraseRoot.createClass(core);
      return phraseRoot.createRoot(opts, linkFn);
    }
  };
});
