// Generated by CoffeeScript 1.6.3
var PhraseNode;

module.exports = PhraseNode = (function() {
  function PhraseNode(properties) {
    var property;
    for (property in properties) {
      this[property] = properties[property];
    }
    this.createdAt = Date.now();
    this.runCount = 0;
  }

  return PhraseNode;

})();
