// Generated by CoffeeScript 1.6.3
var Notice, recursor;

Notice = require('notice');

recursor = require('./phrase/recursor');

require('also')(exports, {}, function(root) {
  var context, validate;
  context = root.context, validate = root.validate;
  context.stack = [];
  return {
    create: validate.args({
      $address: 'phrase.create',
      opts: {
        title: {},
        uuid: {}
      },
      linkFn: {
        $type: Function,
        $description: "\nThis callback is called immediately upon initialization of the\nphrase root. It receives an event publisher that can be used \nto subscribe to phrase events from the local branch.\n"
      }
    }, function(opts, linkFn) {
      context.notice = Notice.create(opts.uuid);
      linkFn(context.notice);
      return recursor.create(root, opts);
    })
  };
});
