// Generated by CoffeeScript 1.6.3
exports.create = function(root) {
  var context, graph, inject;
  context = root.context, inject = root.inject;
  graph = context.graph;
  return {
    graph: graph,
    run: function(opts) {
      var running;
      running = inject.async(function() {});
      return running(opts);
    }
  };
};
