// Generated by CoffeeScript 1.6.3
var Notice, PhraseGraph, PhraseJob, PhraseNode, PhraseRecursor, PhraseToken;

Notice = require('notice');

PhraseToken = require('./phrase_token');

PhraseNode = require('./phrase_node');

PhraseGraph = require('./graph/phrase_graph');

PhraseRecursor = require('./phrase/phrase_recursor');

PhraseJob = require('./phrase/phrase_job');

require('also')(exports, {}, function(root) {
  var context, validate;
  context = root.context, validate = root.validate;
  context.stack = [];
  return {
    createRoot: validate.args({
      $address: 'phrase.createRoot',
      opts: {
        title: {},
        uuid: {},
        leaf: {
          $default: ['end', 'done'],
          $description: "\nThis specifies an array of possible phraseFn arg1 signature names \nthat are used to determine if the phrase function is a leaf.\n\n    eg. \n\n    phraseRegistrar 'phrase text', (end) -> \n\n        # \n        # this is a leaf function\n        # \n"
        },
        timeout: {
          $default: 2000,
          $description: "\nThis specifies how long to allow asynchronous hooks or leaves\nto run before it is assumed they will not complete.\n\neg. \n\nbefore each: (done) -> \n\n    #\n    # has 2 seconds to call done() or it will timeout\n    #\n"
        }
      },
      linkFn: {
        $type: Function,
        $description: "\nThis callback is called immediately upon initialization of the\nphrase root. It receives the phrase tree access token and a\nmiddleware registrar that enables tapping into the chatter \ntraversing the phrase tree's internal message bus.\n"
      }
    }, function(opts, linkFn) {
      context.notice = Notice.create(opts.uuid);
      root.timeout = opts.timeout;
      return function(phraseRootString, phraseRootFn) {
        if (context.walking != null) {
          throw new Error('Phrase root registrar cannot perform concurrent walks');
        }
        if (context.token == null) {
          context.PhraseGraph = PhraseGraph.createClass(root);
          context.PhraseNode = PhraseNode.createClass(root);
          context.PhraseJob = PhraseJob.createClass(root);
          context.token = PhraseToken.create(root);
          PhraseRecursor.walk(root, opts, phraseRootString, phraseRootFn);
          linkFn(context.token, context.notice);
          return;
        }
        return PhraseRecursor.walk(root, opts, phraseRootString, phraseRootFn);
      };
    })
  };
});
