// Generated by CoffeeScript 1.6.3
var EventEmitter, PhraseRunner;

EventEmitter = require('events').EventEmitter;

PhraseRunner = require('./phrase/phrase_runner');

exports.create = function(root) {
  var context, emitter, graph;
  context = root.context;
  graph = context.graph;
  emitter = new EventEmitter;
  emitter.graph = graph;
  emitter.run = function(opts) {
    if (opts == null) {
      opts = {};
    }
    return PhraseRunner.run(root, opts);
  };
  Object.defineProperty(emitter, 'eventProxy', {
    enumerable: false,
    get: function() {
      return function(msg, next) {
        if (msg.context.title === 'phrase::recurse:end') {
          emitter.emit('ready');
        }
        return next();
      };
    }
  });
  return emitter;
};
