// Generated by CoffeeScript 1.6.3
var Notice, PhraseGraph, PhraseRecursor, PhraseToken;

Notice = require('notice');

PhraseToken = require('./phrase_token');

PhraseGraph = require('./graph/phrase_graph');

PhraseRecursor = require('./phrase/phrase_recursor');

require('also')(exports, {}, function(root) {
  var context, validate;
  context = root.context, validate = root.validate;
  context.graph = PhraseGraph.create(root);
  context.token = PhraseToken.create(root);
  context.stack = [];
  return {
    createRoot: validate.args({
      $address: 'phrase.createRoot',
      opts: {
        title: {},
        uuid: {}
      },
      linkFn: {
        $type: Function,
        $description: "\nThis callback is called immediately upon initialization of the\nphrase root. It receives an event publisher that can be used \nto subscribe to phrase events from the local branch.\n"
      }
    }, function(opts, linkFn) {
      context.notice = Notice.create(opts.uuid);
      context.notice.use(context.graph.assembler);
      linkFn(context.token, context.notice);
      return PhraseRecursor.create(root, opts);
    })
  };
});
