// Generated by CoffeeScript 1.6.3
module.exports.create = function(core) {
  return core.assembler = function(msg, next) {
    var newPhraseDefn, newPhraseOpts, srcControl, srcPhrase, srcRoot;
    if (msg.context.title === 'boundry::edge:create') {
      srcPhrase = msg.vertices[0];
      srcControl = msg.control;
      srcRoot = msg.root;
      newPhraseDefn = msg.vertices[1].phrase;
      newPhraseOpts = msg.vertices[1].opts;
      console.log({
        srcPhrase: srcPhrase,
        srcControl: srcControl,
        srcRoot: srcRoot,
        newPhraseDefn: newPhraseDefn,
        newPhraseOpts: newPhraseOpts
      });
    }
    return next();
  };
};
