// Generated by CoffeeScript 1.6.3
var Process, collection;

collection = {};

Process = (function() {
  function Process(core) {
    var _this = this;
    Object.defineProperty(this, 'root', {
      enumerable: true,
      get: function() {
        return function(uuid) {
          return collection[uuid] || (collection[uuid] = {
            uuid: uuid,
            roots: _this.root,
            assembler: core.assembler,
            validate: core.validate,
            inject: core.inject,
            util: core.util
          });
        };
      }
    });
    core.root = this.root;
  }

  return Process;

})();

module.exports = Process;
