// Generated by CoffeeScript 1.6.3
var ChangeSetFactory, pipeline, seq, v1;

v1 = require('node-uuid').v1;

pipeline = require('when/pipeline');

ChangeSetFactory = require('./change_set');

seq = 0;

exports.createClass = function(root) {
  var ChangeSet, PhraseGraph, assembler, context, graphs, notice;
  context = root.context;
  notice = context.notice;
  context.graphs = graphs = {
    latest: null,
    list: {}
  };
  ChangeSet = ChangeSetFactory.createClass(root);
  notice.use(assembler = function(msg, next) {
    if (graphs.latest == null) {
      return next();
    }
    switch (msg.context.title) {
      case 'phrase::recurse:start':
        return next();
      case 'phrase::edge:create':
        return graphs.latest.registerEdge(msg, next);
      case 'phrase::leaf:create':
        return graphs.latest.registerLeaf(msg, next);
      case 'phrase::recurse:end':
        return graphs.latest.createIndexes(msg, next);
      default:
        return next();
    }
  });
  PhraseGraph = (function() {
    function PhraseGraph(opts) {
      var historyLength, localOpts, order, property, uuid, _fn, _i, _j, _len, _len1, _ref, _ref1,
        _this = this;
      if (opts == null) {
        opts = {};
      }
      localOpts = {
        uuid: opts.uuid || v1(),
        version: opts.version || ++seq,
        rootVertex: void 0,
        vertices: {},
        edges: {},
        path2uuid: {},
        uuid2path: {},
        parent: {},
        children: {},
        leaves: []
      };
      graphs.list[localOpts.uuid] = this;
      graphs.latest = this;
      order = [];
      historyLength = 2;
      for (uuid in graphs.list) {
        order.push(uuid);
      }
      _ref = order.slice(0, +(-1 - historyLength) + 1 || 9e9);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        uuid = _ref[_i];
        delete graphs.list[uuid];
      }
      _ref1 = ['uuid', 'version', 'vertices', 'edges', 'path2uuid', 'uuid2path', 'parent', 'children', 'leaves', 'tree'];
      _fn = function(property) {
        return Object.defineProperty(_this, property, {
          get: function() {
            return localOpts[property];
          },
          enumerable: true
        });
      };
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        property = _ref1[_j];
        _fn(property);
      }
      Object.defineProperty(this, 'rootVertex', {
        enumerable: false,
        get: function() {
          return localOpts.rootVertex;
        },
        set: function(value) {
          if (localOpts.rootVertex == null) {
            return localOpts.rootVertex = value;
          }
        }
      });
    }

    PhraseGraph.prototype.createIndexes = function(msg, next) {
      var recurse,
        _this = this;
      if (!(this.leaves.length > 0)) {
        return next();
      }
      msg.tokens = {};
      recurse = function(vertex, stack) {
        var path, text, tokenName, uuid, _i, _len, _ref;
        if (stack == null) {
          stack = [];
        }
        tokenName = vertex.token.name;
        text = vertex.text;
        stack.push("/" + tokenName + "/" + text);
        path = stack.join('');
        _this.path2uuid[path] = vertex.uuid;
        _this.uuid2path[vertex.uuid] = path;
        msg.tokens[path] = vertex.token;
        if (_this.children[vertex.uuid] != null) {
          _ref = _this.children[vertex.uuid];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            uuid = _ref[_i];
            recurse(_this.vertices[uuid], stack);
          }
        }
        return stack.pop();
      };
      recurse(this.rootVertex);
      return next();
    };

    PhraseGraph.prototype.findRoute = function(uuidA, uuidB) {
      var recurse,
        _this = this;
      if (uuidA != null) {
        throw new Error('PhraseGraph.route(null, uuidB) only supports tree route calculation from root to uuidB');
      }
      recurse = function(uuid, uuids) {
        if (uuids == null) {
          uuids = [];
        }
        if (uuid == null) {
          return uuids;
        }
        uuids.unshift(uuid);
        return recurse(_this.parent[uuid], uuids);
      };
      return recurse(uuidB);
    };

    PhraseGraph.prototype.update = function() {
      return pipeline([
        function() {
          return notice.event('graph::compare:start');
        }, function() {
          return new ChangeSet(context.graph, context.graphs.latest).changes;
        }, function(changes) {
          return notice.event('graph::compare:end', {
            changes: changes
          });
        }, function(message) {
          return notice.event('graph::update:start', message);
        }, function(message) {
          if (message.skipChange) {
            return {
              skipped: true
            };
          }
          return ChangeSet.applyChanges(message.changes.uuid);
        }, function(updated) {
          return notice.event('graph::update:end', updated);
        }
      ]);
    };

    PhraseGraph.prototype.registerEdge = function(msg, next) {
      var vertex1, vertex2, _base, _base1, _base2, _name, _name1, _name2, _ref;
      _ref = msg.vertices, vertex1 = _ref[0], vertex2 = _ref[1];
      this.vertices[vertex1.uuid] = vertex1;
      if (this.rootVertex == null) {
        this.rootVertex = vertex1;
      }
      if (vertex2 == null) {
        return next();
      }
      this.vertices[vertex2.uuid] = vertex2;
      (_base = this.edges)[_name = vertex1.uuid] || (_base[_name] = []);
      this.edges[vertex1.uuid].push({
        to: vertex2.uuid
      });
      (_base1 = this.edges)[_name1 = vertex2.uuid] || (_base1[_name1] = []);
      this.edges[vertex2.uuid].push({
        to: vertex1.uuid
      });
      if (msg.type === 'tree') {
        (_base2 = this.children)[_name2 = vertex1.uuid] || (_base2[_name2] = []);
        this.children[vertex1.uuid].push(vertex2.uuid);
        this.parent[vertex2.uuid] = vertex1.uuid;
        if (vertex2.leaf) {
          this.leaves.push(vertex2.uuid);
        }
      }
      return next();
    };

    PhraseGraph.prototype.leavesOf = function(uuid, found) {
      var child_uuid, _i, _len, _ref;
      if (found == null) {
        found = [];
      }
      if (this.vertices[uuid] == null) {
        return found;
      }
      if (this.vertices[uuid].leaf) {
        found.push(this.vertices[uuid]);
        return found;
      }
      _ref = this.children[uuid];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child_uuid = _ref[_i];
        this.leavesOf(child_uuid, found);
      }
      return found;
    };

    return PhraseGraph;

  })();
  Object.defineProperty(PhraseGraph, 'assembler', {
    enumerable: false,
    get: function() {
      return assembler;
    }
  });
  return PhraseGraph;
};
