// Generated by CoffeeScript 1.6.3
var afterHooks, beforeHooks;

beforeHooks = {
  each: [],
  all: []
};

afterHooks = {
  each: [],
  all: []
};

Object.defineProperty(global, 'before', {
  enumerable: false,
  get: function() {
    return function(opts) {
      if (opts == null) {
        opts = {};
      }
      if (typeof opts.each === 'function') {
        beforeHooks.each.push(opts.each);
      }
      if (typeof opts.all === 'function') {
        return beforeHooks.all.push(opts.all);
      }
    };
  }
});

Object.defineProperty(global, 'after', {
  enumerable: false,
  get: function() {
    return function(opts) {
      if (opts == null) {
        opts = {};
      }
      if (typeof opts.each === 'function') {
        afterHooks.each.push(opts.each);
      }
      if (typeof opts.all === 'function') {
        return afterHooks.all.push(opts.all);
      }
    };
  }
});

exports.create = function(root) {
  return {
    beforeAll: beforeHooks.all,
    beforeEach: beforeHooks.each,
    afterEach: afterHooks.each,
    afterAll: afterHooks.all
  };
};
