// Generated by CoffeeScript 1.6.3
var defer;

defer = require('when').defer;

exports.run = function(root, opts) {
  var context, graph, running, uuid;
  context = root.context;
  graph = context.graph;
  uuid = opts.uuid;
  running = defer();
  process.nextTick(function() {
    var error;
    if (uuid == null) {
      error = new Error("missing opts.uuid");
      error.code = 1;
      return running.reject(error);
    }
    if (graph.vertices[uuid] == null) {
      error = new Error("uuid: '" + uuid + "' not in local tree");
      error.code = 2;
      return running.reject(error);
    }
    return running.resolve([]);
  });
  return running.promise;
};
