// Generated by CoffeeScript 1.6.3
var PhraseHooks, RecursorHooks;

RecursorHooks = require('./recursor/hooks');

PhraseHooks = require('./phrase_hooks');

exports.create = function(root, opts, rootString, rootFn) {
  var context, inject, injector, notice, recursor, stack;
  context = root.context, inject = root.inject;
  stack = context.stack, notice = context.notice;
  context.hooks = PhraseHooks.bind(root);
  recursor = function(parentPhraseString, parentPhraseControl) {
    var injectionFn, recursionControl;
    recursionControl = RecursorHooks.bind(root, parentPhraseControl);
    injectionFn = inject.async({
      parallel: false,
      beforeAll: recursionControl.beforeAll,
      beforeEach: recursionControl.beforeEach,
      afterEach: recursionControl.afterEach,
      afterAll: recursionControl.afterAll
    }, function(phraseString, phraseControl, nestedPhraseFn) {
      return nestedPhraseFn(recursor(phraseString, phraseControl));
    });
    Object.defineProperty(injectionFn, 'stack', {
      enumarable: false,
      get: function() {
        return stack;
      }
    });
    return injectionFn;
  };
  injector = recursor('ROOT', {
    phraseToken: {
      name: opts.title,
      uuid: opts.uuid
    },
    timeout: opts.timeout,
    leaf: opts.leaf
  });
  if ((rootString != null) && (rootFn != null)) {
    injector(rootString, rootFn);
  }
  return injector;
};
