// Generated by CoffeeScript 1.6.3
exports.create = function(root) {
  var context, inject, recursor, validate;
  context = root.context, inject = root.inject, validate = root.validate;
  recursor = function(phraseString, parentControl) {
    var injector;
    return injector = inject.async({
      parallel: false,
      beforeAll: function(done) {
        context.emitter.emit('phrase::start');
        return done();
      },
      beforeEach: function(done, inject) {
        var defer;
        defer = inject.defer;
        defer.resolve();
        if (inject.args[2] == null) {
          inject.args[2] = inject.args[1] || inject.args[0] || function() {
            return console.log('NO ARGS');
          };
        }
        return done();
      }
    }, function(phraseString, control, recursor) {
      return recursor();
    });
  };
  return recursor('ROOT', {});
};
