// Generated by CoffeeScript 1.6.3
var RecursorHooks;

RecursorHooks = require('./recursor/hooks');

exports.create = function(root) {
  var context, emitter, inject, recursor, stack;
  context = root.context, inject = root.inject;
  stack = context.stack, emitter = context.emitter;
  recursor = function(parentPhraseString, parentPhraseControl) {
    var injector, recursionControl;
    recursionControl = RecursorHooks.create(root);
    return injector = inject.async({
      parallel: false,
      beforeAll: recursionControl.beforeAll,
      beforeEach: recursionControl.beforeEach,
      afterEach: recursionControl.afterEach,
      afterAll: recursionControl.afterAll
    }, function(phraseString, phraseControl, phraseFn) {
      return phraseFn(recursor(phraseString, phraseControl));
    });
  };
  return recursor('ROOT', {});
};
