// Generated by CoffeeScript 1.6.3
var boundryHandler, defer, join, readdirSync, sequence;

readdirSync = require('fs').readdirSync;

join = require('path').join;

defer = require('when').defer;

sequence = require('when/sequence');

module.exports = boundryHandler = {
  link: function(root, opts) {
    if (opts.directory != null) {
      return boundryHandler.linkDirectory(root, opts);
    }
  },
  linkDirectory: function(root, opts) {
    var filename, notice, regex;
    if (opts.match != null) {
      regex = new RegExp(opts.match);
    } else {
      regex = new RegExp('\\.coffee$');
    }
    notice = root.context.notice;
    return sequence((function() {
      var _i, _len, _ref, _results;
      _ref = boundryHandler.recurse(opts.directory, regex);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        filename = _ref[_i];
        _results.push((function(filename) {
          return function() {
            return notice.event('phrase::boundry:assemble', {
              opts: {
                type: 'directory',
                filename: filename,
                stackpath: 'TODO',
                mode: 'refer'
              }
            });
          };
        })(filename));
      }
      return _results;
    })());
  },
  recurse: function(path, regex, matches) {
    var error, fileOrDirname, nextPath, _i, _len, _ref;
    if (matches == null) {
      matches = [];
    }
    _ref = readdirSync(path);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      fileOrDirname = _ref[_i];
      nextPath = join(path, fileOrDirname);
      try {
        boundryHandler.recurse(nextPath, regex, matches);
      } catch (_error) {
        error = _error;
        if (error.code !== 'ENOTDIR') {
          throw error;
        }
        if (nextPath == null) {
          throw error;
        }
        if (nextPath.match(regex)) {
          matches.push(nextPath);
        }
      }
    }
    return matches;
  }
};
