// Generated by CoffeeScript 1.6.3
var AfterAll, AfterEach, BeforeAll, BeforeEach;

BeforeAll = require('./control/before_all');

BeforeEach = require('./control/before_each');

AfterEach = require('./control/after_each');

AfterAll = require('./control/after_all');

exports.bindControl = function(root, control) {
  var util;
  util = root.util;
  control.isLeaf = function(phrase) {
    var arg1;
    arg1 = (function() {
      try {
        return util.argsOf(phrase.fn)[0];
      } catch (_error) {}
    })();
    if ((arg1 != null) && control.leaf.indexOf(arg1) >= 0) {
      phrase.leaf = true;
      return true;
    }
    return false;
  };
  return {
    beforeAll: BeforeAll.create(root, control),
    beforeEach: BeforeEach.create(root, control),
    afterEach: AfterEach.create(root, control),
    afterAll: AfterAll.create(root, control)
  };
};
