// Generated by CoffeeScript 1.6.3
var BoundryHandler, Control, PhraseHook, PhraseTokenFactory;

Control = require('../recursor/control');

PhraseHook = require('../phrase/hook');

BoundryHandler = require('./boundry_handler');

PhraseTokenFactory = require('../token/phrase_token');

exports.walk = function(root, opts, rootString, rootFn) {
  var PhraseGraph, context, graph, inject, injector, notice, recursor, stack;
  context = root.context, inject = root.inject;
  stack = context.stack, notice = context.notice, graph = context.graph, PhraseGraph = context.PhraseGraph;
  context.hooks = PhraseHook.bind(root);
  context.PhraseToken = PhraseTokenFactory.createClass(root);
  if (graph != null) {
    new PhraseGraph;
  } else {
    context.graph = new PhraseGraph;
  }
  recursor = function(parentPhraseString, parentPhraseControl) {
    var injectionFn, recursionControl;
    recursionControl = Control.bindControl(root, parentPhraseControl);
    injectionFn = inject.async({
      parallel: false,
      beforeAll: recursionControl.beforeAll,
      beforeEach: recursionControl.beforeEach,
      afterEach: recursionControl.afterEach,
      afterAll: recursionControl.afterAll,
      onError: function(done, injectionControl, error) {
        return root.context.token.emit('error', error);
      }
    }, function(phraseString, phraseControl, nestedPhraseFn) {
      var newRecursorFn;
      newRecursorFn = recursor(phraseString, phraseControl);
      Object.defineProperty(newRecursorFn, 'link', {
        enumerable: false,
        get: function() {
          return function(opts) {
            return BoundryHandler.link(root, opts);
          };
        }
      });
      return nestedPhraseFn(newRecursorFn);
    });
    return injectionFn;
  };
  injector = recursor('ROOT', {
    phraseToken: {
      signature: opts.title,
      uuid: opts.uuid
    },
    timeout: opts.timeout,
    boundry: opts.boundry,
    leaf: opts.leaf
  });
  return injector(rootString, rootFn);
};
