// Generated by CoffeeScript 1.6.3
var Control, PhraseHook;

Control = require('../recursor/control');

PhraseHook = require('../phrase/hook');

exports.walk = function(root, opts, rootString, rootFn) {
  var PhraseGraph, context, graph, inject, injector, notice, recursor, stack;
  context = root.context, inject = root.inject;
  stack = context.stack, notice = context.notice, graph = context.graph, PhraseGraph = context.PhraseGraph;
  context.hooks = PhraseHook.bind(root);
  if (graph != null) {
    new PhraseGraph;
  } else {
    context.graph = new PhraseGraph;
  }
  recursor = function(parentPhraseString, parentPhraseControl) {
    var injectionFn, recursionControl;
    recursionControl = Control.bindControl(root, parentPhraseControl);
    injectionFn = inject.async({
      parallel: false,
      beforeAll: recursionControl.beforeAll,
      beforeEach: recursionControl.beforeEach,
      afterEach: recursionControl.afterEach,
      afterAll: recursionControl.afterAll,
      onError: function(done, injectionControl, error) {
        return root.context.token.emit('error', error);
      }
    }, function(phraseString, phraseControl, nestedPhraseFn) {
      var newInjectionFn;
      newInjectionFn = recursor(phraseString, phraseControl);
      return nestedPhraseFn(newInjectionFn);
    });
    return injectionFn;
  };
  injector = recursor('ROOT', {
    phraseToken: {
      name: opts.title,
      uuid: opts.uuid
    },
    timeout: opts.timeout,
    boundry: opts.boundry,
    leaf: opts.leaf
  });
  return injector(rootString, rootFn);
};
