// Generated by CoffeeScript 1.6.3
var Control, PhraseHook, PhraseTokenFactory;

Control = require('../recursor/control');

PhraseHook = require('../phrase/hook');

PhraseTokenFactory = require('../token/phrase_token');

exports.walk = function(root, opts, rootString, rootFn) {
  var PhraseTree, context, inject, injector, notice, recursor, stack, tree, util;
  context = root.context, inject = root.inject, util = root.util;
  stack = context.stack, notice = context.notice, tree = context.tree, PhraseTree = context.PhraseTree;
  context.hooks = PhraseHook.bind(root);
  context.PhraseToken = PhraseTokenFactory.createClass(root);
  if (tree != null) {
    new PhraseTree;
  } else {
    context.tree = new PhraseTree;
  }
  recursor = function(parentPhraseString, parentPhraseControl) {
    var recursionControl;
    recursionControl = Control.bindControl(root, parentPhraseControl);
    return inject.async({
      parallel: false,
      beforeAll: recursionControl.beforeAll,
      beforeEach: recursionControl.beforeEach,
      afterEach: recursionControl.afterEach,
      afterAll: recursionControl.afterAll,
      onError: function(done, injectionControl, error) {
        return root.context.token.emit('error', error);
      }
    }, function(phraseString, phraseControl, nestedPhraseFn) {
      var newRecursorFn;
      newRecursorFn = recursor(phraseString, phraseControl);
      return nestedPhraseFn(newRecursorFn);
    });
  };
  injector = recursor('ROOT', {
    phraseToken: {
      signature: opts.title,
      uuid: opts.uuid
    },
    timeout: opts.timeout,
    boundry: opts.boundry,
    leaf: opts.leaf
  });
  return injector(rootString, rootFn);
};
